apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gobuffalo
resources:
  - namespace.yml
  - toodo.yml
images:
- name: toodo
  newName: localhost:5000/toodo
  newTag: 0.0.1
- name: buffalo
  newName: localhost:5000/toodo-init-container
  newTag: 0.0.1
