apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gobuffalo
resources:
  - namespace.yml
  - toodo.yml
  - postgres-pv.yml
  - postgres-pvc.yml
  - db.yml
images:
- name: toodo
  newName: localhost:5000/toodo
  newTag: 0.0.5
- name: buffalo
  newName: localhost:5000/toodo-init-container
  newTag: 0.0.2
generators:
  - secret-generator.yaml
