apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
data:
    password: ENC[AES256_GCM,data:Hm11bavr1A9lmsAg,iv:DPZbcgkwNuVUCHly7g1P+EcvoFzFd2tITF8ni8iawlo=,tag:65Bd9/QlNPs+/HHrZn74mQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-04-09T13:07:35Z'
    mac: ENC[AES256_GCM,data:zWaWNzDdao8oIRhAk8ZCjM0by7MZEJ0QxrQdWzL8GuDCTVu/nPT4Bq5JOTMspvmemCuXFRHtYZ6Wy4/jR4rojDrJaVvax9fU5Bk4/UsQXZAqbFw3vjvg+4jYPm6X+ed5Bvhyz3aWuCcWvPnUxrmiyLoW5WFraakc1FEaWtaeDI8=,iv:RJ9QrIQ1fvyoNeZEZ53liqpMteY6+mH3jP9UPQ/CejU=,tag:Orsu4JbKzdCKitHWnMDTLQ==,type:str]
    pgp:
    -   created_at: '2020-04-09T13:07:34Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMAyUpShfNkFB/AQgAkFz8/2s8JLizqc09wMAgVMNl7FRv+Xh5gupcl5B/sMmt
            wDyDKILyv8So6mQy1xThATALdsGtQPDr4/q4wJFscR/cq80iCvst4jmj7ejox36y
            rN40mKva7inTUTYN/5fX5BiBWic6fDQPsJdjqTsTCwoEx+7GPqXGT/eHuGkNDLQl
            GWienbkaCoaOEVohbr5ld+p1N2GrAyrY7hc8T2ULff4rmFZmXVj+3BzvvPhbynkS
            8WrfJ7pLDwhDRMCLufFSqg45z4s1iaYk6gBp/T78/aM2M8X3gVL66jDEiJSFf0rQ
            1aDOypds/LaRWVHKkcLp5+EEe/+sXTdEmIJqOXUF2tLgAeSuueSghRwqBGWyFtQ1
            ylUU4ZPW4KzgleHHjeDo4tgivGTgqOWILo1JYZmVn7UcQGkWhO8Sphgz9o/arO+R
            PJg5VcKDhODX5LF7PCvob8+WWMi0p+tUaf3itdqlpeEIfgA=
            =O9ZL
            -----END PGP MESSAGE-----
        fp: FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
