---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toodo
  labels:
    app: toodo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toodo
  template:
    metadata:
      labels:
        app: toodo
    spec:
      serviceAccountName: toodo-svc-role
      initContainers:
        - name: init-mydb
          image: buffalo
          command: ["sh", "-c", "buffalo db create || buffalo db migrate"]
          env:
            - name: GO_ENV
              value: production
            - name: DB_HOST
              value: toodo-postgresql-headless
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgresql-password
            - name: DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASS)@$(DB_HOST):5432/toodo_production?sslmode=disable"
      containers:
        - name: toodo
          image: toodo
          command: ["/bin/app"]
          ports:
            - containerPort: 3000
              protocol: TCP
              name: listen-svc
          env:
            - name: GO_ENV
              value: production
            - name: DB_HOST
              value: toodo-postgresql-headless
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgresql-password
            - name: DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASS)@$(DB_HOST):5432/toodo_production?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: toodo
  labels:
    app: toodo
spec:
  selector:
    app: toodo
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: listen-svc
      name: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: toodo-svc-role
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: toodo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: toodo.buffalo
    http:
      paths:
      - path: /
        backend:
          serviceName: toodo
          servicePort: 3000
